apiVersion: batch/v1
kind: Job
metadata:
  name: cv
spec:
  template:
    spec:
      containers:
        - name: cv
          image: zzyo/dl_jobs:v1
          command: [ "sh", "-c" ]
          args: [ "cd /workspace && python dqn.py" ]
          resources:
            limits:
              cpu: 1000m
              memory: 2100Mi
            requests:
              cpu: 1000m
              memory: 2100Mi
      restartPolicy: OnFailure
  metadata:
    name: cv


